### PR TITLE
Create gems.yml

### PR DESCRIPTION
**Pull request by acouch**
issue #24

### CODE REVIEW

**Comment by janette** [comment]
maybe this stuff too
http://mgalalm.com/2014/12/01/install-sass-and-compass-on-ubuntu-14-04/

```
sudo apt-get update
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties
sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
echo “source ~/.rvm/scripts/rvm” >> ~/.bashrc
rvm install 2.1.2
rvm use 2.1.2 –default
ruby -v
gem install compass
gem install sass
```

**Comment by acouch** [comment]
for latest ruby and rvm we should use https://github.com/rvm/rvm1-ansible

**Comment by acouch** [comment]
That latest commit should do it. Lets get a review.

**Comment by acouch** [comment]
Need to switch to this branch, update the config.yml file and `ansible-galaxy install -r requirements.txt --force``

**Pull request merged**
